name: darrick
favicon: null
layout_spectrum: 0.25419
typography_spectrum: 0.50772
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4e4e4'
    - '#242424'
    - '#737373'
    - '#e7282d'
    - '#36a0c8'
  brandStrength: 0
  lightness: 0.988080273848027
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
